development:
  adapter: postgresql
  database: jerisa_development
  host: localhost
  username: jerisa
  password: jerisa
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: jerisa_test
  host: localhost
  username: jerisa
  password: jerisa
  pool: 5
  timeout: 5000
